version: "2"
volumes:
  mongodata:
services:
  scraper:
    build:
      context: ./scraperAPI
      dockerfile: Dockerfile
    image: scraper-api
    ports:
      - "8080:8080"
    expose:
      - 8080
    container_name: Scraper-API
  
  aggregator:
    build:
      context: ./aggregatorAPI
      dockerfile: Dockerfile
    image: aggregator-api
    ports:
      - "8081:8081"
    container_name: Aggregator-API
  
  database:
    image: mongo:4.4.2
    ports:
      - "27017:27017"
    container_name: MongoDB
    volumes:
      - type: volume
        source: mongodata
        target: /data/db